// import type { Metadata } from "next";
// import "./globals.css";
// import { AuthSessionProvider } from "@/components/auth/session-provider";
// import { Toaster } from "@/components/ui/sonner"

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="antialiased">
//         <AuthSessionProvider>
//           {children}
//           <Toaster />
//         </AuthSessionProvider>
//       </body>
//     </html>
//   );
// }






import type { Metadata } from "next";
import "./globals.css";

import { AuthSessionProvider } from "@/components/auth/session-provider";
import { Toaster } from "@/components/ui/sonner";
import { BrandColorProvider } from "@/components/dashboard/brand-color-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dashboardColorScript = `
  try {
    const allowedColors = [
      "blue",
      "violet",
      "emerald",
      "rose",
      "amber",
      "indigo"
    ];

    const savedColor =
      window.localStorage.getItem(
        "pos-dashboard-color"
      );

    const initialColor =
      savedColor &&
      allowedColors.includes(savedColor)
        ? savedColor
        : "blue";

    document.documentElement.setAttribute(
      "data-dashboard-color",
      initialColor
    );
  } catch {
    document.documentElement.setAttribute(
      "data-dashboard-color",
      "blue"
    );
  }
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-dashboard-color="blue"
      suppressHydrationWarning
    >
      <head>
        <script
          id="dashboard-color-initializer"
          dangerouslySetInnerHTML={{
            __html: dashboardColorScript,
          }}
        />
      </head>

      <body className="antialiased">
        <AuthSessionProvider>
          <BrandColorProvider>
            {children}
          </BrandColorProvider>

          <Toaster />
        </AuthSessionProvider>
      </body>
    </html>
  );
}