// import type { Metadata } from "next";
// import "./globals.css";
// import { AuthSessionProvider } from "@/components/auth/session-provider";
// import { Toaster } from "@/components/ui/sonner"

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="antialiased">
//         <AuthSessionProvider>
//           {children}
//           <Toaster />
//         </AuthSessionProvider>
//       </body>
//     </html>
//   );
// }






import type { Metadata } from "next";
import "./globals.css";

import { AuthSessionProvider } from "@/components/auth/session-provider";
import { Toaster } from "@/components/ui/sonner";
import { BrandColorProvider } from "@/components/dashboard/brand-color-provider";
import { ShopTimezoneProvider } from "@/components/shop-timezone-provider";
import { CurrencyProvider } from "@/components/currency-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-dashboard-color="blue"
    >
<body className="antialiased">
        <AuthSessionProvider>
          <BrandColorProvider>
            <ShopTimezoneProvider>
            <CurrencyProvider>
            {children}
            </CurrencyProvider>
            </ShopTimezoneProvider>
          </BrandColorProvider>

          <Toaster />
        </AuthSessionProvider>
      </body>
    </html>
  );
}
